version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.x
      python: 3.7
    commands:
      - echo "Received environment variables..."
      - echo $AWS_REGION
      - echo $USER_POOL_ID
      - echo $WEB_CLIENT_ID
      - echo $BASEPATH
      - python --version
      - node -v
      - npm -v
  build:
    commands:
      - npm install
      - cd client
      - npm install
      - npm run build

artifacts:
  files:
    - client/build/*
