version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - npm install
  pre_build:
    commands:
      - "echo wait condition url: $WAIT_CONDITION"
  build:
    commands:
      - "npx serverless package"
  post_build:
    commands:
      - "curl -X PUT -H 'Content-Type:' --data-binary '{\"Status\": \"SUCCESS\",\"Reason\": \"build complete\",\"UniqueId\": \"ID1234\",\"Data\": \"Codebuild has completed the API build project.\"}' $WAIT_CONDITION"

artifacts:
  EncryptionDisabled: "true"
  Location: $TRAINING_APP_BUCKET
  Packaging: "NONE"
  Type: s3
  Discard-paths: yes
  Files:
    - .serverless/nlpjs.zip


