version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.x
      python: 3.7
    commands:
      - echo "Received environment variables..."
      - echo "Region: $AWS_REGION"
      - echo "User Pool Id: $USER_POOL_ID"
      - python --version
      - node -v
      - npm -v
  build:
    commands:
      - echo "Begin build phase..."
      - npm install
      - cd client
      - npm install
      - npm run build

artifacts:
  files:
    - public/*
