version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.13.0
      python: 3.7
    commands:
      - echo "Build environment install phase complete"
      - python --version
      - node -v
      - npm -v
  build:
    commands:
      - echo "Begin build phase..."
      - cd client
      - npm install
      - npm run build

artifacts:
  files:
    - client/build/*
