version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12.x
      python: 3.7
    commands:
      - echo "Received environment variables..."
      - echo $AWS_REGION
      - echo $USER_POOL_ID
      - echo $WEB_CLIENT_ID
      - echo $BASEPATH
      - python --version
      - node -v
      - npm -v
      - virtualenv -p `which python3` venv3
      - source venv3/bin/activate
      - pip install -r requirements.txt
      - python aws-deployment/configure_aws_exports.py --user_pool_id=$USER_POOL_ID --client_id=$WEB_CLIENT_ID --region=$AWS_REGION
      - python aws-deployment/configure_swagger.py --basepath=$BASEPATH
  build:
    commands:
      - npm install
      - cd client
      - npm install
      - npm run build

artifacts:
  files:
    - client/build/*
